/*
 * This file was automatically generated by EvoSuite
 * Wed Dec 06 20:48:08 GMT 2023
 */

package org.apache.commons.net.discard;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.net.InetAddress;
import org.apache.commons.net.discard.DiscardUDPClient;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.mock.java.net.MockInetAddress;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class DiscardUDPClient_ESTest extends DiscardUDPClient_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      DiscardUDPClient discardUDPClient0 = new DiscardUDPClient();
      byte[] byteArray0 = new byte[5];
      InetAddress inetAddress0 = MockInetAddress.getLoopbackAddress();
      discardUDPClient0.open(1, inetAddress0);
      discardUDPClient0.send(byteArray0, 1, inetAddress0, (int) (byte)6);
      assertTrue(discardUDPClient0.isOpen());
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      DiscardUDPClient discardUDPClient0 = new DiscardUDPClient();
      byte[] byteArray0 = new byte[5];
      InetAddress inetAddress0 = MockInetAddress.getLoopbackAddress();
      discardUDPClient0.open(1, inetAddress0);
      discardUDPClient0.send(byteArray0, inetAddress0);
      assertEquals("127.0.0.1", inetAddress0.getHostAddress());
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      DiscardUDPClient discardUDPClient0 = new DiscardUDPClient();
      byte[] byteArray0 = new byte[4];
      discardUDPClient0.open();
      InetAddress inetAddress0 = MockInetAddress.getLoopbackAddress();
      discardUDPClient0.send(byteArray0, 0, inetAddress0);
      assertFalse(inetAddress0.isLinkLocalAddress());
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      DiscardUDPClient discardUDPClient0 = new DiscardUDPClient();
      byte[] byteArray0 = new byte[5];
      InetAddress inetAddress0 = MockInetAddress.getLoopbackAddress();
      // Undeclared exception!
      try { 
        discardUDPClient0.send(byteArray0, (int) (byte) (-64), inetAddress0, 0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // illegal length
         //
         verifyException("java.net.DatagramPacket", e);
      }
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      DiscardUDPClient discardUDPClient0 = new DiscardUDPClient();
      byte[] byteArray0 = new byte[3];
      // Undeclared exception!
      try { 
        discardUDPClient0.send(byteArray0, (int) (byte) (-41), (InetAddress) null);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // illegal length
         //
         verifyException("java.net.DatagramPacket", e);
      }
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      DiscardUDPClient discardUDPClient0 = new DiscardUDPClient();
      byte[] byteArray0 = new byte[5];
      InetAddress inetAddress0 = MockInetAddress.getLoopbackAddress();
      // Undeclared exception!
      try { 
        discardUDPClient0.send(byteArray0, 1, inetAddress0, (int) (byte)6);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // DatagramSocket
         //
         verifyException("java.util.Objects", e);
      }
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      DiscardUDPClient discardUDPClient0 = new DiscardUDPClient();
      byte[] byteArray0 = new byte[2];
      InetAddress inetAddress0 = MockInetAddress.anyLocalAddress();
      // Undeclared exception!
      try { 
        discardUDPClient0.send(byteArray0, inetAddress0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // DatagramSocket
         //
         verifyException("java.util.Objects", e);
      }
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      DiscardUDPClient discardUDPClient0 = new DiscardUDPClient();
      byte[] byteArray0 = new byte[4];
      InetAddress inetAddress0 = MockInetAddress.getLoopbackAddress();
      // Undeclared exception!
      try { 
        discardUDPClient0.send(byteArray0, 0, inetAddress0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // DatagramSocket
         //
         verifyException("java.util.Objects", e);
      }
  }
}
