/*
 * This file was automatically generated by EvoSuite
 * Thu Dec 07 09:34:19 GMT 2023
 */

package org.apache.commons.net.pop3;

import org.junit.Test;
import static org.junit.Assert.*;
import org.apache.commons.net.pop3.POP3MessageInfo;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class POP3MessageInfo_ESTest extends POP3MessageInfo_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      POP3MessageInfo pOP3MessageInfo0 = new POP3MessageInfo();
      assertEquals(0, pOP3MessageInfo0.size);
      
      pOP3MessageInfo0.size = (-2393);
      String string0 = pOP3MessageInfo0.toString();
      assertEquals("Number: 0. Size: -2393. Id: null", string0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      POP3MessageInfo pOP3MessageInfo0 = new POP3MessageInfo(0, "");
      assertEquals(0, pOP3MessageInfo0.number);
      assertEquals((-1), pOP3MessageInfo0.size);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      POP3MessageInfo pOP3MessageInfo0 = new POP3MessageInfo((-2289), (String) null);
      assertEquals((-2289), pOP3MessageInfo0.number);
      assertEquals((-1), pOP3MessageInfo0.size);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      POP3MessageInfo pOP3MessageInfo0 = new POP3MessageInfo((-1), (-1));
      assertEquals((-1), pOP3MessageInfo0.number);
      assertEquals((-1), pOP3MessageInfo0.size);
  }
}
