/*
 * This file was automatically generated by EvoSuite
 * Thu Dec 07 09:36:33 GMT 2023
 */

package org.apache.commons.net.pop3;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.io.Reader;
import org.apache.commons.net.pop3.POP3Client;
import org.apache.commons.net.pop3.POP3MessageInfo;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class POP3Client_ESTest extends POP3Client_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      POP3Client pOP3Client0 = new POP3Client();
      pOP3Client0.setState(1);
      // Undeclared exception!
      try { 
        pOP3Client0.retrieveMessageTop(50, 3458);
        fail("Expecting exception: IllegalStateException");
      
      } catch(IllegalStateException e) {
         //
         // Socket is not connected
         //
         verifyException("org.apache.commons.net.pop3.POP3", e);
      }
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      POP3Client pOP3Client0 = new POP3Client();
      pOP3Client0.setState(1);
      // Undeclared exception!
      try { 
        pOP3Client0.retrieveMessage(7);
        fail("Expecting exception: IllegalStateException");
      
      } catch(IllegalStateException e) {
         //
         // Socket is not connected
         //
         verifyException("org.apache.commons.net.pop3.POP3", e);
      }
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      POP3Client pOP3Client0 = new POP3Client();
      pOP3Client0.setState(0);
      // Undeclared exception!
      try { 
        pOP3Client0.login((String) null, (String) null, (String) null);
        fail("Expecting exception: IllegalStateException");
      
      } catch(IllegalStateException e) {
         //
         // Socket is not connected
         //
         verifyException("org.apache.commons.net.pop3.POP3", e);
      }
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      POP3Client pOP3Client0 = new POP3Client();
      pOP3Client0.setState(0);
      // Undeclared exception!
      try { 
        pOP3Client0.login((String) null, "MD5", "Connection closed without indication.");
        fail("Expecting exception: IllegalStateException");
      
      } catch(IllegalStateException e) {
         //
         // Socket is not connected
         //
         verifyException("org.apache.commons.net.pop3.POP3", e);
      }
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      POP3Client pOP3Client0 = new POP3Client();
      pOP3Client0.setState(0);
      // Undeclared exception!
      try { 
        pOP3Client0.login("", "", "kRm5Mtj+");
        fail("Expecting exception: IllegalStateException");
      
      } catch(IllegalStateException e) {
         //
         // Socket is not connected
         //
         verifyException("org.apache.commons.net.pop3.POP3", e);
      }
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      POP3Client pOP3Client0 = new POP3Client();
      pOP3Client0.setState(3050);
      boolean boolean0 = pOP3Client0.login("Obq-ffb2Z", "Obq-ffb2Z", "Obq-ffb2Z");
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      POP3Client pOP3Client0 = new POP3Client();
      pOP3Client0.setState(0);
      // Undeclared exception!
      try { 
        pOP3Client0.login("l#", "LOGIN");
        fail("Expecting exception: IllegalStateException");
      
      } catch(IllegalStateException e) {
         //
         // Socket is not connected
         //
         verifyException("org.apache.commons.net.pop3.POP3", e);
      }
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      POP3Client pOP3Client0 = new POP3Client();
      pOP3Client0.setState(3070);
      boolean boolean0 = pOP3Client0.login("Obq-ffb2Z", "\r\n");
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      POP3Client pOP3Client0 = new POP3Client();
      pOP3Client0.setState(1);
      // Undeclared exception!
      try { 
        pOP3Client0.listUniqueIdentifier(14);
        fail("Expecting exception: IllegalStateException");
      
      } catch(IllegalStateException e) {
         //
         // Socket is not connected
         //
         verifyException("org.apache.commons.net.pop3.POP3", e);
      }
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      POP3Client pOP3Client0 = new POP3Client();
      pOP3Client0.setState(1);
      // Undeclared exception!
      try { 
        pOP3Client0.listMessage((-987));
        fail("Expecting exception: IllegalStateException");
      
      } catch(IllegalStateException e) {
         //
         // Socket is not connected
         //
         verifyException("org.apache.commons.net.pop3.POP3", e);
      }
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      POP3Client pOP3Client0 = new POP3Client();
      // Undeclared exception!
      try { 
        pOP3Client0.capa();
        fail("Expecting exception: IllegalStateException");
      
      } catch(IllegalStateException e) {
         //
         // Socket is not connected
         //
         verifyException("org.apache.commons.net.pop3.POP3", e);
      }
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      POP3Client pOP3Client0 = new POP3Client();
      POP3MessageInfo pOP3MessageInfo0 = pOP3Client0.status();
      assertNull(pOP3MessageInfo0);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      POP3Client pOP3Client0 = new POP3Client();
      pOP3Client0.setState(1);
      // Undeclared exception!
      try { 
        pOP3Client0.status();
        fail("Expecting exception: IllegalStateException");
      
      } catch(IllegalStateException e) {
         //
         // Socket is not connected
         //
         verifyException("org.apache.commons.net.pop3.POP3", e);
      }
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      POP3Client pOP3Client0 = new POP3Client();
      Reader reader0 = pOP3Client0.retrieveMessageTop((-2547), 0);
      assertNull(reader0);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      POP3Client pOP3Client0 = new POP3Client();
      Reader reader0 = pOP3Client0.retrieveMessageTop((-210), (-210));
      assertNull(reader0);
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      POP3Client pOP3Client0 = new POP3Client();
      Reader reader0 = pOP3Client0.retrieveMessage(0);
      assertNull(reader0);
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      POP3Client pOP3Client0 = new POP3Client();
      pOP3Client0.setState(1);
      // Undeclared exception!
      try { 
        pOP3Client0.reset();
        fail("Expecting exception: IllegalStateException");
      
      } catch(IllegalStateException e) {
         //
         // Socket is not connected
         //
         verifyException("org.apache.commons.net.pop3.POP3", e);
      }
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      POP3Client pOP3Client0 = new POP3Client();
      boolean boolean0 = pOP3Client0.reset();
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      POP3Client pOP3Client0 = new POP3Client();
      pOP3Client0.setState(1);
      // Undeclared exception!
      try { 
        pOP3Client0.noop();
        fail("Expecting exception: IllegalStateException");
      
      } catch(IllegalStateException e) {
         //
         // Socket is not connected
         //
         verifyException("org.apache.commons.net.pop3.POP3", e);
      }
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      POP3Client pOP3Client0 = new POP3Client();
      boolean boolean0 = pOP3Client0.noop();
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      POP3Client pOP3Client0 = new POP3Client();
      pOP3Client0.setState(1);
      // Undeclared exception!
      try { 
        pOP3Client0.logout();
        fail("Expecting exception: IllegalStateException");
      
      } catch(IllegalStateException e) {
         //
         // Socket is not connected
         //
         verifyException("org.apache.commons.net.pop3.POP3", e);
      }
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      POP3Client pOP3Client0 = new POP3Client();
      // Undeclared exception!
      try { 
        pOP3Client0.logout();
        fail("Expecting exception: IllegalStateException");
      
      } catch(IllegalStateException e) {
         //
         // Socket is not connected
         //
         verifyException("org.apache.commons.net.pop3.POP3", e);
      }
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      POP3Client pOP3Client0 = new POP3Client();
      boolean boolean0 = pOP3Client0.login("Obq-ffb2Z", "Obq-ffb2Z", "Obq-ffb2Z");
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      POP3Client pOP3Client0 = new POP3Client();
      boolean boolean0 = pOP3Client0.login("Obq-ffb2Z", "\r\n");
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      POP3Client pOP3Client0 = new POP3Client();
      POP3MessageInfo[] pOP3MessageInfoArray0 = pOP3Client0.listUniqueIdentifiers();
      assertNull(pOP3MessageInfoArray0);
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      POP3Client pOP3Client0 = new POP3Client();
      pOP3Client0.setState(1);
      // Undeclared exception!
      try { 
        pOP3Client0.listUniqueIdentifiers();
        fail("Expecting exception: IllegalStateException");
      
      } catch(IllegalStateException e) {
         //
         // Socket is not connected
         //
         verifyException("org.apache.commons.net.pop3.POP3", e);
      }
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      POP3Client pOP3Client0 = new POP3Client();
      POP3MessageInfo pOP3MessageInfo0 = pOP3Client0.listUniqueIdentifier(110);
      assertNull(pOP3MessageInfo0);
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      POP3Client pOP3Client0 = new POP3Client();
      POP3MessageInfo[] pOP3MessageInfoArray0 = pOP3Client0.listMessages();
      assertNull(pOP3MessageInfoArray0);
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      POP3Client pOP3Client0 = new POP3Client();
      pOP3Client0.setState(1);
      // Undeclared exception!
      try { 
        pOP3Client0.listMessages();
        fail("Expecting exception: IllegalStateException");
      
      } catch(IllegalStateException e) {
         //
         // Socket is not connected
         //
         verifyException("org.apache.commons.net.pop3.POP3", e);
      }
  }

  @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      POP3Client pOP3Client0 = new POP3Client();
      POP3MessageInfo pOP3MessageInfo0 = pOP3Client0.listMessage(2);
      assertNull(pOP3MessageInfo0);
  }

  @Test(timeout = 4000)
  public void test30()  throws Throwable  {
      POP3Client pOP3Client0 = new POP3Client();
      pOP3Client0.setState(1);
      // Undeclared exception!
      try { 
        pOP3Client0.deleteMessage(1631);
        fail("Expecting exception: IllegalStateException");
      
      } catch(IllegalStateException e) {
         //
         // Socket is not connected
         //
         verifyException("org.apache.commons.net.pop3.POP3", e);
      }
  }

  @Test(timeout = 4000)
  public void test31()  throws Throwable  {
      POP3Client pOP3Client0 = new POP3Client();
      boolean boolean0 = pOP3Client0.deleteMessage(0);
      assertFalse(boolean0);
  }
}
